# Auto-Bump Scoop Bucket Workflow
# Save as: .github/workflows/bump-insightctl.yml in RailguardAI/scoop-bucket repository

name: Bump insightctl
on:
  repository_dispatch:
    types: [new_release]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.3)'
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SCOOP_TOKEN }}

      - name: Update manifest
        run: |
          # Get tag from input or repository_dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${{ github.event.client_payload.tag }}"
          fi

          # Remove 'v' prefix if present
          VERSION="${TAG#v}"

          echo "Updating insightctl manifest to $TAG ($VERSION)"

          # Download checksums
          curl -sL -o checksums.txt "https://github.com/RailguardAI/railguard-mvp/releases/download/$TAG/checksums.txt"

          # Extract Windows SHA256
          WINDOWS_SHA=$(grep 'insightctl-windows-amd64.exe$' checksums.txt | awk '{print $1}')

          echo "Windows SHA: $WINDOWS_SHA"

          # Update manifest using jq
          jq --arg version "$VERSION" \
             --arg tag "$TAG" \
             --arg hash "sha256:$WINDOWS_SHA" \
             '.version = $version |
              .architecture."64bit".url = "https://github.com/RailguardAI/railguard-mvp/releases/download/\($tag)/insightctl-windows-amd64.exe" |
              .architecture."64bit".hash = $hash' \
             bucket/insightctl.json > bucket/insightctl.json.tmp

          mv bucket/insightctl.json.tmp bucket/insightctl.json

      - name: Commit and push
        run: |
          git config user.name "release-bot"
          git config user.email "bot@users.noreply.github.com"
          git add bucket/insightctl.json
          git commit -m "insightctl: bump to ${{ github.event.client_payload.tag || github.event.inputs.tag }}" || exit 0
          git push
